name: Build Horizon Documentation UI bundle

on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: install
        run: |
          npm install --quiet --no-progress --cache=.cache/npm

  verify:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: lint
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp lint

  deploy:
    runs-on: ubuntu-latest
    needs: [setup, verify]
    env:
      GITHUB_RELEASE_URL: https://github.com/${{ github.repository }}/releases/latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: Install Dependencies
        run: |
          sudo apt install zip -y
          sudo apt install gh -y

      - name: bundle-stable
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp bundle

      - name: bundle-stable - Artifact
        run: |
          gh release upload ${{github.event.release.tag_name}} build/ui-bundle.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: pages
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp preview:build
          rm -rf public/_/{helpers,layouts,partials}
          zip -r public.zip public

      - name: pages - Artifact
        run: |
          gh release upload ${{github.event.release.tag_name}} public.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
