name: Deploy Horizon Documentation UI

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: install
        run: |
          npm install --quiet --no-progress --cache=.cache/npm

  verify:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: lint
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp lint

  deploy:
    runs-on: ubuntu-latest
    needs: [setup, verify]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .cache/npm
          key: npm

      - name: bundle-stable
        if: github.ref == 'refs/heads/master'
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp bundle

      - name: bundle-stable - Artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: ui-bundle
          path: build/ui-bundle.zip

      - name: bundle-dev
        if: github.ref != 'refs/heads/master'
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp bundle

      - name: bundle-dev - Artifact
        uses: actions/upload-artifact@v4
        if: github.ref != 'refs/heads/master'
        with:
          name: ui-bundle
          path: build/ui-bundle.zip
          retention-days: 1

      - name: pages
        if: github.ref == 'refs/heads/master'
        run: |
          npm install --quiet --no-progress --cache=.cache/npm
          node_modules/.bin/gulp preview:build
          rm -rf public/_/{helpers,layouts,partials}

      - name: pages - Artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
