name: Trigger Webhook for building the Documentation

on:
  push:
    branches:
      - v*

env:
  REPO_NAME: 'docs.evertrust.fr'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger Webhook
        run: |
          curl -XPOST -H "Authorization: Bearer ${{ secrets.TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" "https://api.github.com/repos/${{github.repository_owner}}/${{env.REPO_NAME}}/dispatches" --data '{"event_type": "deploy-docs"}'
